### ISSUE TITLE
Path delimiter problems

### ISSUE THREAD

**Issue by krainboltgreene** [krainboltgreene/library.io#3]
Right now the dependency fetching code uses "/" file delimiters and that's not going to work. Need to figure out if we need to build our own switcher, or if Io has one itself.

**Comment by gatesphere** [comment]
Io has one on it's own, called Path.

Ex:

```
Path with("some", "directory", "structure") => "some/directory/structure".  
```

This is platform independent... on Windows boxes it should render as "some\directory\structure"

**Comment by krainboltgreene** [comment]
Awesome, thanks. I'll make the change now.
